version: '3.8'

# GPU EC2インスタンス用の設定ファイル - Ollamaサービスのみを含む
# 使用方法: docker-compose -f docker-compose.gpu.yml up -d

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    environment:
      # 環境変数で設定可能なパラメータ
      - OLLAMA_HOST=${OLLAMA_HOST:-0.0.0.0}
      - OLLAMA_MODELS_PATH=${OLLAMA_MODELS_PATH:-/root/.ollama}
    # Docker Compose V2形式のGPU設定
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: ${GPU_COUNT:-1}
              capabilities: [gpu]

volumes:
  ollama_data: